### PR TITLE
Add readthedocs config

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Blocked by https://github.com/sphinx-doc/sphinx/issues/3488

**Review by rm-hull — APPROVED** [review]
http://luma-emulator.readthedocs.io/en/rtd-update/api-documentation.html - all good

**Comment by thijstriemstra** [comment]
@rm-hull well the link to core doesn't work in http://luma-emulator.readthedocs.io/en/rtd-update/api-documentation.html#luma.emulator.device.emulator, perhaps the intersphinx mapping is missing?

**Update:** the intersphinx for core is indeed missing: https://github.com/rm-hull/luma.emulator/blob/master/doc/conf.py#L356

**Comment by rm-hull** [comment]
Got it, will push a fix now.
Thanks for all your efforts on this BTW 

🍻

**Comment by thijstriemstra** [comment]
No worries, cheers!

**Pull request merged**
