### PR TITLE
Drop support for Python 3.5 and test against Python 3.9

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull any idea what's up with that last failing test?

**Review by rm-hull — APPROVED** [review]

**Review by rm-hull — APPROVED** [review]

**Comment by rm-hull** [comment]
Probably the version of pillow changing has subtly changed how pixels are rendered, and so the ascii blocks rendered output has also slightly changed..

**Comment by rm-hull** [comment]
The py39 build failure looks to me like pygame is not compatible with python 3.9 yet

**Comment by rm-hull** [comment]
This is what the asciiblock render looks like now:
image
vs. previously:
image
There are subtle differences in the rendering of the red oval shape

**Pull request merged**
